name: 'data_takehome'

config-version: 2
version: '0.1'

profile: 'data_takehome'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

seeds: 
  +docs:
    node_color: '#cd7f32'

models:
  data_takehome:
    suvera_task:
      staging:
        +materialized: view
        +docs:
          node_color: 'blue'
        +schema: staging
      marts:
        +materialized: table
        +docs:
          node_color: 'gold'
        +schema: marts
      intermediate:
        +materialized: table
        +docs:
          node_color: 'silver'
        +schema: intermediate
      data_quality:
        +materialized: table
        +docs:
          node_color: 'red'
        +schema: data_quality
    
